name: AxTrade
version: '${project.version}'
main: com.artillexstudios.axtrade.AxTrade
api-version: '1.21'
folia-supported: true

permissions:
  axtrade.admin:
    default: op
  axtrade.trade:
    default: true
  axtrade.toggle:
    default: true

softdepend:
  - PlaceholderAPI
  - PlayerPoints
  - Vault
